### ISSUE TITLE
Path request for version 1.5

### ISSUE THREAD

**Issue by belg4mit** [jaw0/Term-Pager#1]
Fixes RT issues, other bugs, and adds many features including a more featureful example. I'd be happy to upload a new version to PAUSE if granted commit bits.

P.S. Providing a patch because I do not have a functional installation of git at the moment

[patch.txt](https://github.com/jaw0/Term-Pager/files/3586854/patch.txt)
[tp_pl.txt](https://github.com/jaw0/Term-Pager/files/3586855/tp_pl.txt)

**Comment by jaw0** [comment]
I am not going to even try to decipher this impenetrable  "great wall of diff".
perhaps a nice subclass?

**Comment by belg4mit** [comment]
A sub-class isn't really a viable option here since many of the changes are to the core of the code to allow processing of live pipes, acceptance of control and meta keystrokes (including arrows), as well as fleshing out of the documentation... not just alternate keybindings, or addition of a few subroutines to allow progressive matching, etc. (although there is some of the latter as well).

As for the large chunk of text, I apologize for the inconvenience but unfortunately, as previously noted, I do not have access to a functioning git; due to outdated SSL libraries effectively requiring a full OS reinstall, github.com will not communicate with my client. The patch was intended less to be read by hand (though as a unified diff, not so difficult nor different from what git diff would give I think), but applied and then inspected as you wish.  If you prefer, I have attached the altered versions of the files directly [Term-Pager-1.50.tar.gz](https://github.com/jaw0/Term-Pager/files/3597934/Term-Pager-1.50.tar.gz); the Pager.pm therein has a few extra minor differences (below) from before, because I had begun playing with (Term::)Terminfo

```
--- Pager.pm~   2019-09-07 13:16:50.887826364 -0400
+++ Pager.pm    2019-09-07 15:55:03.035413184 -0400
@@ -195,6 +195,10 @@
            @dims{'rows','cols'} = ($1,$2) if `stty size` =~ /^(\d+)\s+(\d+)$/;
            $param{speed} = $1 if `stty speed` =~ /^(\d+)$/;
        }
+       else{
+           $dims{rows} = `tput lines` || $dims{rows};
+           $dims{cols} = `tput cols` || $dims{cols};
+       }
     }
 
     #screen is vt100 compatible but does not list sf?!
@@ -203,6 +207,10 @@
        $ENV{TERM} = 'vt100';
     }
 
+#cm=>cup, ce=>el, cl=>clear, sf=>ind, sr=>ri
+#md=>bold, me=>sgr0, mr=>rev, us=>smul

```
